<?php
return [
    [
        "title" => "Appartamento accogliente",
        "city" => "Roma",
        "street_name" => "Via Roma",
        "street_number" => "123",
        "postal_code" => "00100",
        "latitude" => 41.9028,
        "longitude" => 12.4964,
        "country" => "Italia",
        "country_code" => "IT",
    ],
    [
        "title" => "Vista panoramica sul mare",
        "city" => "Barcelona",
        "street_name" => "Carrer de la Marina",
        "street_number" => "456",
        "postal_code" => "08005",
        "latitude" => 41.3888,
        "longitude" => 2.1724,
        "country" => "Spagna",
        "country_code" => "ES",
    ],
    [
        "title" => "Appartamento moderno",
        "city" => "Parigi",
        "street_name" => "Rue de Rivoli",
        "street_number" => "789",
        "postal_code" => "75001",
        "latitude" => 48.8588,
        "longitude" => 2.3509,
        "country" => "Francia",
        "country_code" => "FR",
    ],
    [
        "title" => "Casa tranquilla in campagna",
        "city" => "Firenze",
        "street_name" => "Via dei Colli",
        "street_number" => "234",
        "postal_code" => "50123",
        "latitude" => 43.7696,
        "longitude" => 11.2558,
        "country" => "Italia",
        "country_code" => "IT",
    ],
    [
        "title" => "Loft moderno",
        "city" => "Berlino",
        "street_name" => "Friedrichstraße",
        "street_number" => "567",
        "postal_code" => "10117",
        "latitude" => 52.5200,
        "longitude" => 13.4050,
        "country" => "Germania",
        "country_code" => "DE",
    ],
    [
        "title" => "Casa con giardino",
        "city" => "Lisbona",
        "street_name" => "Rua Augusta",
        "street_number" => "890",
        "postal_code" => "1100-048",
        "latitude" => 38.7083,
        "longitude" => -9.1384,
        "country" => "Portogallo",
        "country_code" => "PT",
    ],
    [
        "title" => "Appartamento storico",
        "city" => "Vienna",
        "street_name" => "Schönbrunner Schloßstraße",
        "street_number" => "1234",
        "postal_code" => "1130",
        "latitude" => 48.1858,
        "longitude" => 16.3121,
        "country" => "Austria",
        "country_code" => "AT",
    ],
    [
        "title" => "Villetta panoramica",
        "city" => "Atene",
        "street_name" => "Leof. Vasileos Konstantinou",
        "street_number" => "5678",
        "postal_code" => "11635",
        "latitude" => 37.9795,
        "longitude" => 23.7162,
        "country" => "Grecia",
        "country_code" => "GR",
    ],
    [
        "title" => "Appartamento sul lago",
        "city" => "Zurigo",
        "street_name" => "Seestrasse",
        "street_number" => "910",
        "postal_code" => "8002",
        "latitude" => 47.3574,
        "longitude" => 8.5497,
        "country" => "Svizzera",
        "country_code" => "CH",
    ],
    [
        "title" => "Casa di campagna",
        "city" => "Dublino",
        "street_name" => "Merrion Square",
        "street_number" => "1112",
        "postal_code" => "D02 K224",
        "latitude" => 53.3404,
        "longitude" => -6.2577,
        "country" => "Irlanda",
        "country_code" => "IE",
    ],
];
