<?php
return [
    [
        "title" => "Appartamento nel centro storico",
        "city" => "Roma",
        "street_name" => "Via del Corso",
        "street_number" => "123",
        "postal_code" => "00186",
        "latitude" => 41.8975,
        "longitude" => 12.4721,
        "country" => "Italia",
        "country_code" => "IT"
    ],
    [
        "title" => "Appartamento panoramico vicino al Colosseo",
        "city" => "Roma",
        "street_name" => "Via dei Fori Imperiali",
        "street_number" => "45",
        "postal_code" => "00184",
        "latitude" => 41.8925,
        "longitude" => 12.4853,
        "country" => "Italia",
        "country_code" => "IT"
    ],
    [
        "title" => "Accogliente monolocale nel quartiere Trastevere",
        "city" => "Roma",
        "street_name" => "Via della Lungaretta",
        "street_number" => "67",
        "postal_code" => "00153",
        "latitude" => 41.8897,
        "longitude" => 12.4693,
        "country" => "Italia",
        "country_code" => "IT"
    ],
    [
        "title" => "Appartamento moderno vicino alla Stazione Termini",
        "city" => "Roma",
        "street_name" => "Via Giovanni Giolitti",
        "street_number" => "10",
        "postal_code" => "00185",
        "latitude" => 41.9015,
        "longitude" => 12.5001,
        "country" => "Italia",
        "country_code" => "IT"
    ],
    [
        "title" => "Bilocale elegante nel quartiere Parioli",
        "city" => "Roma",
        "street_name" => "Via Archimede",
        "street_number" => "15",
        "postal_code" => "00197",
        "latitude" => 41.9148,
        "longitude" => 12.4916,
        "country" => "Italia",
        "country_code" => "IT"
    ],
    [
        "title" => "Attico con terrazza vista Pantheon",
        "city" => "Roma",
        "street_name" => "Via della Rotonda",
        "street_number" => "12",
        "postal_code" => "00186",
        "latitude" => 41.8986,
        "longitude" => 12.4766,
        "country" => "Italia",
        "country_code" => "IT"
    ],
    [
        "title" => "Monolocale luminoso a Trastevere",
        "city" => "Roma",
        "street_name" => "Via dei Salumi",
        "street_number" => "32",
        "postal_code" => "00153",
        "latitude" => 41.8882,
        "longitude" => 12.4709,
        "country" => "Italia",
        "country_code" => "IT"
    ],
    [
        "title" => "Villetta panoramica",
        "city" => "Atene",
        "street_name" => "Leof. Vasileos Konstantinou",
        "street_number" => "5678",
        "postal_code" => "11635",
        "latitude" => 37.9795,
        "longitude" => 23.7162,
        "country" => "Grecia",
        "country_code" => "GR",
    ],
    [
        "title" => "Appartamento sul lago",
        "city" => "Zurigo",
        "street_name" => "Seestrasse",
        "street_number" => "910",
        "postal_code" => "8002",
        "latitude" => 47.3574,
        "longitude" => 8.5497,
        "country" => "Svizzera",
        "country_code" => "CH",
    ],
    [
        "title" => "Casa di campagna",
        "city" => "Dublino",
        "street_name" => "Merrion Square",
        "street_number" => "1112",
        "postal_code" => "D02 K224",
        "latitude" => 53.3404,
        "longitude" => -6.2577,
        "country" => "Irlanda",
        "country_code" => "IE",
    ],
];
